# Generated by Django 4.1 on 2022-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymlocation", name="gym", field=models.TextField(default=" "),
        ),
    ]
