# Generated by Django 4.1 on 2022-09-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="score",),
    ]
