# Generated by Django 4.1 on 2022-09-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguhome', '0002_alter_trainer_mapurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='gym',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='inform',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
