# Generated by Django 4.1 on 2022-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguhome', '0003_alter_trainer_gym_alter_trainer_inform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gym_loaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.CharField(default='', max_length=30)),
                ('location', models.TextField(default='')),
            ],
        ),
    ]
