# Generated by Django 4.1 on 2022-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0003_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score", name="score", field=models.IntegerField(default=9),
        ),
    ]
