# Generated by Django 4.1 on 2022-09-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0004_alter_score_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score", name="score", field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="score",
            name="trainer_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="nuguhome.trainer"
            ),
        ),
    ]
