# Generated by Django 4.1 on 2022-09-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuguhome', '0004_gym_loaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gym_loaction',
            new_name='gym_location',
        ),
    ]
