# Generated by Django 4.1 on 2022-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuguhome', '0005_rename_gym_loaction_gym_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='gymlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.TextField(default='')),
                ('location', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='gym_location',
        ),
    ]
