# Generated by Django 4.1 on 2022-09-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0005_alter_score_score_alter_score_trainer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("searchtext", models.TextField(default="")),
            ],
        ),
    ]
