# Generated by Django 4.1 on 2022-09-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0007_trainer_starsocre"),
    ]

    operations = [
        migrations.RemoveField(model_name="trainer", name="starsocre",),
    ]
