# Generated by Django 4.1 on 2022-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0008_remove_trainer_starsocre"),
    ]

    operations = [
        migrations.CreateModel(
            name="score",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(default=9)),
            ],
        ),
    ]
