# Generated by Django 4.1 on 2022-09-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0013_alter_score_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="score", old_name="id", new_name="created_at",
        ),
    ]
