# Generated by Django 4.1 on 2022-09-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0014_rename_id_score_created_at"),
    ]

    operations = [
        migrations.DeleteModel(name="score",),
    ]
