# Generated by Django 4.1 on 2022-09-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0018_score"),
    ]

    operations = [
        migrations.DeleteModel(name="score",),
    ]
