# Generated by Django 4.1 on 2022-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nuguhome", "0019_delete_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="asdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adsfasdf", models.CharField(max_length=20)),
            ],
        ),
    ]
